### ISSUE TITLE
Confirm the price of an order

### ISSUE THREAD

**Issue by siferati** [tirafesi/TDIN01#9]
Whenever the current quote drops and there are other pending
selling orders, those are suspended during a time interval (for testing let’s use just 1 minute
or less). During this suspension time the order emitter can confirm the new quote or withdraw
the order. If, after the suspension period, there is no action from the emitter the system
assumes a confirmation, making them active again at the current quote. In the same way,
whenever the quote rises and there are other pending purchase orders, those are suspended
for confirmation of the new price or for withdraw. Again, the system presumes that the orders
are confirmed if there is no action from the emitter during the suspension period.
[x] Add an integer called "available" to each order
[x] Only orders with value available != 0 are suspended
[ ] When an order is going to be suspended: 1. increment the value of "available";  2. notify user that new quote must be updated or deleted; 3. schedule a task 1 minute after time
[x] when the task sheduled performs, if value of available = 0 means user accepted the new quote and there's nothing to do, if order_id does not exists means that the user did not accept the new order and there's nothing to do, else subtract one to the value of available
[x] add a parameter to SetQuote so the server can know if the quote was changed because of a seller or a buyer
[ ] create a method in IClient to receive a list of orders that don't have the correct quote

**Comment by Bragado** [comment]
Feito
